import './globals.css'
import Header from './header'
import Footer from './footer'

export const metadata = {
  title: 'My Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/x-icon" href="/favicon.ico"/>
      </head>
      <body className='font-sans'>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
